# SPDX-License-Identifier: CECILL-B
# Copyright © 2015-2019 EOST UNISTRA, Storengy SAS, Damian Kula
# Copyright © 2019-2023 Contributors to the Noiz project.

include: # include our template script collection
    - local: "/.gitlab/templates/linting.yml"
    - local: "/.gitlab/templates/documentation.yml"


image: python:3.8

stages:
  - testing
  - linting
  - documentation
  - documentation-deployment
  - image-building
  - system-testing
  - downstream

cache:
  key: mypy-pip-pytest-cache
  paths:
    - .mypy-cache/
    - .pytest_cache/
    - .cache/pip
  policy: pull-push

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  UNITTESTING_IMAGE_TAG: $CI_REGISTRY_IMAGE:unittesting
  POSTGRES_IMAGE_TAG: $CI_REGISTRY_IMAGE:postgres
  STABLE_IMAGE_TAG: $CI_REGISTRY_IMAGE:stable
  LATEST_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  DIND_IMAGE: docker:19.03.12
  DIND_SERVICE: docker:19.03.12-dind
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

test-noiz:
  parallel:
    matrix:
      - TESTING_IMAGE:
          - python:3.9-buster
          - python:3.10-buster
#          - python:3.11-buster # to be activated when constraint are released
#          - python:3.12-buster # to be activated when constraint are released

  image: $TESTING_IMAGE
  stage: testing
  before_script:
    - python -m pip install --upgrade pip hatch
  script:
    - hatch run test:cov

.image_building_parent:
  stage: image-building
  image: $DIND_IMAGE
  services:
    - $DIND_SERVICE
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - export DOCKER_BUILDKIT=1
  after_script:
    - docker push $CI_REGISTRY_IMAGE

test_build:
  extends: .image_building_parent
  script:
    - docker build -f docker/noiz-image/Dockerfile --cache-from $LATEST_IMAGE_TAG -t $LATEST_IMAGE_TAG .
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      changes:
        - docker/noiz-image/Dockerfile

stable_build:
  extends: .image_building_parent
  script:
    - docker build -f docker/noiz-image/Dockerfile -t $LATEST_IMAGE_TAG -t $STABLE_IMAGE_TAG .
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - docker/noiz-image/Dockerfile

build_unittesting:
  extends: .image_building_parent
  script:
    - docker build -f docker/unittest-image/Dockerfile -t $UNITTESTING_IMAGE_TAG .
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - docker/unittest-image/Dockerfile

build_postgres:
  extends: .image_building_parent
  script:
    - docker build -f docker/postgres-image/Dockerfile -t $POSTGRES_IMAGE_TAG .
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - docker/postgres-image/Dockerfile

.system_test_parent:
  stage: system-testing
  image: $LATEST_IMAGE_TAG
  services:
    - name: $POSTGRES_IMAGE_TAG
      alias: postgres
  variables:
    POSTGRES_HOST: postgres
    POSTGRES_PORT: "5432"
    POSTGRES_USER: noiztest
    POSTGRES_PASSWORD: noiztest
    POSTGRES_DB: noiztest
    PROCESSED_DATA_DIR: /processed-data-dir
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - python -m pip install --upgrade pip hatch
    - python -m pip install -r requirements.txt
    - python -m pip install .
    - mkdir -p $PROCESSED_DATA_DIR
#    - noiz db init
    - noiz db migrate
    - noiz db upgrade
#
#api_system_tests:
#  extends: .system_test_parent
#  script:
#    - pytest --cov=noiz --runapi

cli_system_tests:
  extends: .system_test_parent
  script:
    - SQLALCHEMY_WARN_20=1 pytest --cov=noiz --runcli
    - coverage xml
  artifacts:
    reports:
      coverage_report:
        coverage_format:  cobertura
        path: coverage.xml

cli_system_tests_parallel:
  extends: .system_test_parent
  variables:
    NOIZ_RUN_SYSTEM_TESTS_PARALLEL: "True"
  script:
    - SQLALCHEMY_WARN_20=1 pytest --runcli
  allow_failure: true
