image: continuumio/miniconda3:latest

before_script:
  - apt-get update && apt-get upgrade -yy
  - conda create -c conda-forge -c heavelock -n noiz-test python=3.7 --file=requirements.txt --yes

test-noiz:
  script:
    - source activate noiz-test
    - pytest --cov=noiz