image: python:3.8

stages:
  - testing
  - linting
  - documentation
  - documentation-deployment
  - image-building
  - downstream

.install_noiz_complete: &install_noiz_complete
  - python -m pip install --upgrade pip setuptools wheel
  - python -m pip install --no-cache-dir -r requirements.txt
  - python -m pip install .

test-noiz:
  before_script:
    - *install_noiz_complete

  stage: testing
  script:
    - pytest --cov=noiz

type-check:
#  before_script:
#    - *install_noiz
  stage: linting
  script:
    - python -m pip install -r requirements-test.txt
    - mypy src/noiz

flake8:
 stage: linting
 script:
   - python -m pip install flake8
   - flake8 .

build-docs:
  stage: documentation
  before_script:
    - *install_noiz_complete
  script:
  - apt-get update && apt-get install build-essential -yy
  - sphinx-apidoc -f -o docs noiz
  - cd docs
  - make html
  artifacts:
    paths:
    - docs/_build/html/
#  only:
#    - master

pages:
  stage: documentation-deployment
  image: alpine
  script:
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master

test_build:
  stage: image-building
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  variables:
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_TAG: $CI_REGISTRY_IMAGE/test:$CI_COMMIT_REF_SLUG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  except:
  - master

latest_build:
  stage: image-building
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  variables:
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
  - master

trigger_airflow_master:
  stage: downstream
  image: alpine
  script:
    - apk update && apk add curl
    - "curl -X POST -F token=$TOKEN_TRIGGER_MASTER_AIRFLOW -F ref=master https://gitlab.com/api/v4/projects/13151521/trigger/pipeline"
  only:
  - master
