image: continuumio/miniconda3:latest

stages:
  - test_stage
  - linting_stage
  - docs_stage
  - deploy_stage

before_script:
  - apt-get update && apt-get upgrade -yy
  - conda create -c conda-forge -c heavelock -n noiz-test python=3.7 --file=requirements.txt --yes
  - source activate noiz-test
  - pip install sqlalchemy-stubs

test-noiz:
  stage: test_stage
  script:
    - source activate noiz-test
    - pytest --cov=noiz

black-check:
  stage: linting_stage
  script:
    - source activate noiz-test
    - black --verbose --check noiz

type-check:
  stage: linting_stage
  script:
    - source activate noiz-test
    - mypy noiz

docs_buil:
  stage: docs_stage
  script:
  - apt-get install build-essential -yy
  - pip install -r requirements-docs.txt
  - cd docs
  - make html
  artifacts:
    paths:
    - docs/_build/html/

pages:
  stage: deploy_stage
  script:
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
#  only:
#  - master
