# SPDX-License-Identifier: CECILL-B
# Copyright © 2015-2019 EOST UNISTRA, Storengy SAS, Damian Kula
# Copyright © 2019-2023 Contributors to the Noiz project.

repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks.git
        rev: v4.4.0
        hooks:
            - id: trailing-whitespace
            - id: check-yaml
              args:
                  - --unsafe
            - id: check-toml
            - id: end-of-file-fixer
            - id: trailing-whitespace
    -   repo: https://github.com/pycqa/flake8
        rev: 3.8.4
        hooks:
            - id: flake8
    -   repo: https://github.com/PyCQA/doc8.git
        rev: v1.1.1
        hooks:
            - id: doc8
    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v1.7.0
        hooks:
        -   id: mypy
            additional_dependencies: [
                "types-toml ~=0.10.8.7",
                "pydantic ~=2.4",
                "sqlalchemy ==2.0.23",
                "types-python-dateutil ==2.8.2",
            ]
            args:
                - --ignore-missing-imports
                - --install-types
            exclude: tests/
