repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
#-   repo: git://github.com/luismayta/pre-commit-mypy
#    sha: 'b9595c1285cd8a9a032b7f759c75e08f74974bb6'  # Use the sha you want to point at
#    hooks:
#    -   id: mypy
#        args:
#        - --ignore-missing-imports