# SPDX-License-Identifier: CECILL-B
# Copyright © 2015-2019 EOST UNISTRA, Storengy SAS, Damian Kula
# Copyright © 2019-2023 Contributors to the Noiz project.

repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks.git
        rev: v5.0.0
        hooks:
            - id: trailing-whitespace
            - id: check-yaml
              args:
                  - --unsafe
            - id: check-toml
            - id: end-of-file-fixer
            - id: trailing-whitespace
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.11.13
      hooks:
        # Run the linter.
        - id: ruff-check
          args: [ --fix ]
        # Run the formatter.
        - id: ruff-format
    -   repo: https://github.com/PyCQA/doc8.git
        rev: v1.1.2
        hooks:
            - id: doc8
#    -   repo: https://github.com/pre-commit/mirrors-mypy
#        rev: v1.16.0
#        hooks:
#        -   id: mypy
#            additional_dependencies: [sqlalchemy-stubs~=0.3, pydantic~=1.7.2]
#            args:
#                - --ignore-missing-imports
#            exclude: tests/
