repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    -   id: mypy
        additional_dependencies: [sqlalchemy-stubs~=0.3]
        args:
            - --ignore-missing-imports
        exclude: tests/
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
-   repo: https://github.com/PyCQA/doc8.git
    rev: master
    hooks:
    - id: doc8
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v3.3.0  # Use the ref you want to point at
    hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace
