# SPDX-License-Identifier: CECILL-B
# Copyright © 2015-2019 EOST UNISTRA, Storengy SAS, Damian Kula
# Copyright © 2019-2023 Contributors to the Noiz project.

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "noiz"
dynamic = ["version"]
readme = "README.rst"
license = {file = "LICENSE.rst"}
authors = [
    { name = "Damian Kula", email = "heavelock@gmail.com" },
]
dependencies = [
    "more-itertools >=8.11",
    "sqlalchemy >=1.4.0, <2.0",
    "click >=8.0.3",
    "environs >=9.3.5",
    "flask ==2.0.2",
    "flask-sqlalchemy ==2.5.1",
    "flask-migrate ==3.1.0",
    "loguru >=0.5.3",
    "matplotlib ==3.5.0",
    "numpy ==1.21.4",
    "obspy ==1.2.2",
    "pandas ==1.3.4",
    "psycopg2-binary ==2.9.2",
    "pydantic ~=1.8",
    "scipy ==1.7.2",
    "tqdm >=4.62.3",
    "toml>=0.10.2",
    "utm >=0.7.0",
    "dask[complete] ==2021.11.2",
    "pendulum ~=2.1",
]
[project.optional-dependencies]
test = [
    "pytest ==6.2.5",
    "pytest-check ==1.0.4",
    "pytest-cov ==3.0.0",
    "pytest-dependency ==0.5.1",
    "pytest-mock ==3.6.1",
    "mock==4.0.3",
    "mypy ==0.910",
    "sqlalchemy-stubs ==0.4",
    "flake8 ==4.0.1",
    "types-python-dateutil ==2.8.2",
    "types-toml ==0.10.1",
]
docs = [
    "sphinx ==4.3.0",
    "sphinx-autobuild ==2021.3.14",
    "sphinx-autoapi ==1.8.4",
    "sphinx-paramlinks ==0.5.2",
    "sphinx-autodoc-typehints ==1.12.0",
    "autodoc ==0.5.0",
    "furo ==2021.11.23",
    "doc8 ==0.10.1",
]

[project.scripts]
noiz = "noiz.cli:cli"

[tool.hatch.version]
path = "src/noiz/__init__.py"

[tool.hatch.build.targets.sdist]
include = [
    "/src",
    "/tests",
]

[tool.doc8]
max_line_length = 120
