exclude = [
            ".git",
            "__pycache__",
            "docs/conf.py",
            "old",
            "build",
            "dist",
            ".ipynb_checkpoints",
            "examples",
            "migrations",
            ".venv",
]

line-length = 119
#max-complexity = 18

[lint]
# E121: continuation line under-indented for hanging indent
# E123: closing bracket does not match indentation of opening bracket’s line
# E126: continuation line over-indented for hanging indent
# E133: closing bracket is missing indentation
#   this is an Error shown for one alternative form of closing bracket,
#   closing it without indentation with regard to opening line. This gets
#   raised when --hang-closing is selected to allow the form with 4 spaces
#   as indent (which is valid according to PEP8 but raised by pycodestyle)
# E24: multiple spaces after ‘,’
# E226: missing whitespace around arithmetic operator
# E402: module level import not at top of file
# E704: multiple statements on one line (def)
# W503: line break before binary operator
# W504: line break after binary operator
# W605 invalid escape sequence (does not recognize latex in matplotlib labels)
# E741: ambiguous variable name 'l'
ignore = [
            "E203",
            "E266",
            "E501",
            "F403",
            "F401",
#            "E121",
#            "E123",
#            "E126",
#            "E133",
            "E24",
            "E226",
            "E402",
#            "E704",
#            "W503",
#            "W504",
            "W605",
            "E741",
            "B011", # Do not `assert False`
            "C901", # Ignore complexity at least for now
            "B905", # zip-without-explicit-strict because mypy hates it
        ]
select = [
            "B",
            "C",
            "E",
            "F",
            "W",
#            "T4",
            "B9",
]
