# SPDX-License-Identifier: CECILL-B
# Copyright © 2015-2019 EOST UNISTRA, Storengy SAS, Damian Kula
# Copyright © 2019-2025 Contributors to the Noiz project.

FROM postgres:13
COPY db-init-scripts/* /docker-entrypoint-initdb.d/
