"""empty message

Revision ID: 25b25bb2f017
Revises: 
Create Date: 2019-06-24 17:35:16.624638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b25bb2f017'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filepath', sa.UnicodeText(), nullable=True),
    sa.Column('filetype', sa.UnicodeText(), nullable=True),
    sa.Column('add_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('readeable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processingconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('use_winter_time', sa.Boolean(), nullable=True),
    sa.Column('f_sampling_out', sa.Integer(), nullable=True),
    sa.Column('downsample_filt_order', sa.Integer(), nullable=True),
    sa.Column('window_length_spectrum_sec', sa.Float(), nullable=True),
    sa.Column('window_spectrum_overlap', sa.Float(), nullable=True),
    sa.Column('window_spectrum_reject_method', sa.String(length=50), nullable=True),
    sa.Column('window_spectrum_crit_std', sa.Float(), nullable=True),
    sa.Column('window_spectrum_crit_quantile', sa.Float(), nullable=True),
    sa.Column('window_spectrum_num_for_stat', sa.Integer(), nullable=True),
    sa.Column('sequence_length_sec', sa.Float(), nullable=True),
    sa.Column('sequence_overlap', sa.Float(), nullable=True),
    sa.Column('sequence_reject_method', sa.String(length=50), nullable=True),
    sa.Column('sequence_crit_std', sa.Float(), nullable=True),
    sa.Column('sequence_crit_quantile', sa.Float(), nullable=True),
    sa.Column('sequence_num_for_stat', sa.Integer(), nullable=True),
    sa.Column('sequence_reject_tolerance_on_window_spectrum', sa.Float(), nullable=True),
    sa.Column('f_min_reject_crit', sa.Float(), nullable=True),
    sa.Column('f_max_reject_crit', sa.Float(), nullable=True),
    sa.Column('filter_type', sa.String(length=50), nullable=True),
    sa.Column('taper_time_type', sa.String(length=50), nullable=True),
    sa.Column('taper_time_width_periods', sa.Float(), nullable=True),
    sa.Column('taper_time_width_min_samples', sa.Integer(), nullable=True),
    sa.Column('taper_time_width_max_proportion', sa.Float(), nullable=True),
    sa.Column('taper_freq_type', sa.String(length=50), nullable=True),
    sa.Column('taper_freq_width_proportion', sa.Float(), nullable=True),
    sa.Column('taper_freq_width_min_samples', sa.Integer(), nullable=True),
    sa.Column('taper_freq_width_max_freqs', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processingconfig')
    op.drop_table('file')
    # ### end Alembic commands ###
