"""empty message

Revision ID: d705d31bf616
Revises: 25b25bb2f017
Create Date: 2019-06-24 19:23:09.900290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd705d31bf616'
down_revision = '25b25bb2f017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'file', ['filepath'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file', type_='unique')
    # ### end Alembic commands ###
