[BeamformingParams]
qcone_config_id = 1
min_freq = 1.2
max_freq = 1.3
slowness_x_min = -2
slowness_x_max = 2
slowness_y_min = -2
slowness_y_max = 2
slowness_step = 0.025
window_length_minimum_periods = 15
window_step_fraction = 0.5
perform_statistical_reject = "False"
n_sigma_stat_reject = 2.5
prop_bad_freqs_stat_reject = 0.5
save_average_beamformer_abspower = "False"
save_all_beamformers_abspower = "False"
save_average_beamformer_relpower = "True"
save_all_beamformers_relpower = "False"
perform_deconvolution_all = "False"
perform_deconvolution_average = "True"
save_all_arf = "False"
save_average_arf = "True"
arf_enlarge_ratio = 3
sparsity_max = 1
sigma_angle_kernels =  45
sigma_slowness_kernels_ratio_to_ds = 2
rms_threshold_deconv = 0.01
alpha_reg = 1
rel_rms_thresh_admissible_slowness = 2
rel_rms_stop_crit_increase_sparsity = 0.25
extract_peaks_average_beamformer_abspower = "False"
extract_peaks_all_beamformers_abspower = "False"
extract_peaks_average_beamformer_relpower = "True"
extract_peaks_all_beamformers_relpower = "False"
neighborhood_size_xaxis_fraction = 0.1
maxima_threshold = 0.0
best_point_count = 10
beam_portion_threshold = 0.1
semblance_threshold  = -1e9
velocity_threshold = -1e9
prewhiten = "False"
method = "beamforming"
used_component_codes = [ "Z"]
minimum_trace_count = 6 
