[PPSDParams]
datachunk_params_id = 1
segment_length = 600
segment_step = 500
freq_min = 0.1
freq_max = 5
resample = "True"
resampled_frequency_start = 0.2
resampled_frequency_stop = 4
resampled_frequency_step = 0.1
rejected_windows_quantile = 0.1
save_all_windows = "False"